version: "3"
containers:
- name: workstation
  image: ubuntu
  shell: /bin/bash
  memory: 1024
- name: cloud-client
  image: gcr.io/instruqt/cloud-client
  shell: /bin/bash
  ports:
  - 80
gcp_projects:
- name: gcpproject
  services:
  - cloudresourcemanager.googleapis.com
  - compute.googleapis.com
  - container.googleapis.com
