slug: helm
type: track
title: Helm chart
teaser: Learn how to install helm charts with Instruqt
description: |-
  Learn how to build tracks with a pre-installed helm chart in this template.


  **This track will provide you with:**
    - A virtual machine with a kubernetes cluster
    - Helm already installed on the machine
    - NGINX ingress controller pre-installed on the kubernetes cluster
icon: https://raw.githubusercontent.com/instruqt/instruqt-track-assets/master/track-icons/helm.png
tags: []
owner: templates
developers:
  - victor@instruqt.com
  - gerson@instruqt.com
private: false
published: true
