##############################################################################
# Instruqt Github Actions Workflow
#
# This workflow file and its actions will run a validate/push/test cycle on
# one or more Instruqt tracks directories in your repo. Each job targets a
# separate directory of tracks. All the tracks in each directory must belong
# to the same organization.
#
##############################################################################
name: Instruqt Validate, Push, and Test
concurrency: 1
on:
  push:
    branches:
      - main
jobs:
  Instruqt-Demos-Test:
    runs-on: ubuntu-latest
    env:
      # Set these values to match your environment. Your token should be 
      # stored as a Github secret in your tracks repo.
      ORGANIZATION_SLUG: templates
      TRACK_DIR: instruqt-tracks
      INSTRUQT_TOKEN: ${{ secrets.INSTRUQT_TOKEN }}
    strategy:
      matrix:
        # List of track directories inside TRACK_DIR
        # Add any directories that you want to include.
        tracks:
        - aws-cloud-account
        - container
        - docker-vm
        - kubernetes
        - kubernetes-cluster
        - vscode-typescript
    steps:
      - run: echo "üìù Instruqt validate/push/test job was triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Track Validate
        uses: ./.github/actions/instruqt-track-validate
        with:
          path: ${{ env.TRACK_DIR }}/${{ matrix.tracks }}
      - name: Track Push
        uses: ./.github/actions/instruqt-track-push
        with:
          path: ${{ env.TRACK_DIR }}/${{ matrix.tracks }}
      - name: Instruqt Track Test
        uses: ./.github/actions/instruqt-track-test
        with:
          path: ${{ env.TRACK_DIR }}/${{ matrix.tracks }}
      - run: echo "ü§ñ This job's status is ${{ job.status }}."